version: "3.9"

services:
  backend:
    build: ./mensajes-backend
    container_name: django_backend
    expose:
      - "8000"
    volumes:
      - ./mensajes-backend:/app
    restart: always

  frontend:
    build: ./mensajes-front
    container_name: react_frontend
    expose:
      - "80"
    restart: always

  nginx:
    image: nginx:latest
    container_name: mensajes_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    restart: always
